package main

import (
	"context"
	"flag"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"
)

func main() {
	relayURL := flag.String("relay-url", envOrDefault("RELAY_FRONTEND_URL", "http://localhost:3000"), "relay HTTP base URL (used only when --relay-socket is empty)")
	relaySocket := flag.String("relay-socket", envOrDefault("RELAY_FRONTEND_SOCKET", ""), "relay frontend Unix socket path (preferred when running under the relay orchestrator)")
	relayToken := flag.String("relay-token", envOrDefault("RELAY_FRONTEND_TOKEN", ""), "Bearer token for relay's frontend API")
	dataDir := flag.String("data-dir", envOrDefault("RELAY_SCHEDULER_DATA", ""), "Data directory for tasks and logs")
	socketPath := flag.String("socket", envOrDefault("RELAY_SCHEDULER_SOCKET", ""), "Unix socket this service listens on. Defaults to {data-dir}/relayscheduler.sock. relay learns the path via manifest registration; standalone clients dial it directly.")
	internalToken := flag.String("token", envOrDefault("RELAY_SCHEDULER_TOKEN", ""), "Bearer token required on every inbound request. Empty → auto-generated (not logged). Under relay the token travels via manifest registration.")
	flag.Parse()

	if *dataDir == "" {
		dir, err := os.UserConfigDir()
		if err != nil {
			dir, _ = os.UserHomeDir()
		}
		*dataDir = filepath.Join(dir, "relayScheduler")
	}
	if err := os.MkdirAll(*dataDir, 0700); err != nil {
		slog.Error("failed to create data directory", "path", *dataDir, "error", err)
		os.Exit(1)
	}

	// Listener address: relayScheduler picks where it binds. relay (if running)
	// learns the path via manifest registration; standalone clients dial it
	// directly. Default keeps the socket under data-dir so it's discoverable.
	if *socketPath == "" {
		*socketPath = filepath.Join(*dataDir, "relayscheduler.sock")
	}
	// Bearer token: relayScheduler picks its own. Auto-generated if unset so the
	// listener is never unauthenticated. Under relay the token travels via
	// manifest registration. We deliberately do not log the auto-generated value
	// so it doesn't end up in shipped log files.
	tokenAutoGenerated := *internalToken == ""
	if tokenAutoGenerated {
		*internalToken = generateBearerToken()
	}

	slog.Info("starting relayScheduler",
		"relayURL", *relayURL,
		"relaySocket", *relaySocket,
		"socket", *socketPath,
		"dataDir", *dataDir,
		"tokenAutoGenerated", tokenAutoGenerated)
	zone, offset := time.Now().Zone()
	slog.Info("system timezone", "zone", zone, "offsetSeconds", offset)

	client := NewLLMClient(*relayURL, *relaySocket, *relayToken)
	store := NewTaskStore(*dataDir)
	logStore := NewLogStore(filepath.Join(*dataDir, "task-logs"))
	hub := NewHub(store)
	scheduler := NewScheduler(client, store, logStore, hub)

	// Load tasks from store and start the wall-clock ticker.
	if err := scheduler.LoadAllTasks(); err != nil {
		slog.Error("failed to load tasks", "error", err)
	}
	scheduler.Start()

	// HTTP + WS API. Served on a Unix socket (relay-issued under the
	// orchestrator, or under data-dir standalone) and dispatched to by relay's
	// front door. relayLLM already owns "/ws", so task events go on "/ws/tasks".
	mux := http.NewServeMux()
	RegisterRoutes(mux, store, scheduler, logStore)
	mux.HandleFunc("/ws/tasks", HandleWS(hub))

	// bearerAuth sits in front of the mux so unauthenticated requests never
	// reach a real handler (and never register a WS hub client).
	server := &http.Server{Handler: bearerAuth(*internalToken, mux)}

	if err := os.MkdirAll(filepath.Dir(*socketPath), 0o700); err != nil {
		slog.Error("failed to create socket parent dir", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	// Remove any stale socket file from a previous crashed run.
	_ = os.Remove(*socketPath)
	listener, err := net.Listen("unix", *socketPath)
	if err != nil {
		slog.Error("failed to listen on socket", "path", *socketPath, "error", err)
		os.Exit(1)
	}
	if err := os.Chmod(*socketPath, 0o600); err != nil {
		slog.Warn("failed to chmod socket", "path", *socketPath, "error", err)
	}

	// Tell relay (if present) where to dispatch front-door traffic. Standalone
	// runs are a clean no-op. Goroutine so a slow bridge round-trip doesn't
	// delay the listener accepting traffic.
	go maybeRegisterManifest(*socketPath, *internalToken)

	serverErr := make(chan error, 1)
	go func() {
		slog.Info("API listening", "socket", *socketPath)
		serverErr <- server.Serve(listener)
	}()

	// Wait for shutdown or server failure.
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	select {
	case err := <-serverErr:
		if err != nil && err != http.ErrServerClosed {
			slog.Error("API server failed", "error", err)
		}
	case <-sig:
	}

	slog.Info("shutting down")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = server.Shutdown(ctx)
	_ = listener.Close()
	_ = os.Remove(*socketPath)
	scheduler.Stop()
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
